### ISSUE TITLE
Where i can read docks?

### ISSUE THREAD

**Issue by mirikking** [apify/fingerprint-suite#166]
I can't find documentation anywhere, can anyone tell me where to look?

**Comment by barjin** [comment]
Hello! 
The documentation of this project has been deprecated, as it added next to no value and was outdated all the time. In my eyes, this project is so small, it's (mostly) self-explanatory. The only source of truth now is the [README file](https://github.com/apify/fingerprint-suite/blob/master/README.md) in the root of the repository, which contains all the important info to get started.

Do you have any specific question you can't find an answer for? Maybe I can help :)

**Comment by mirikking** [comment]
> Hello! The documentation of this project has been deprecated, as it added next to no value and was outdated all the time. In my eyes, this project is so small, it's (mostly) self-explanatory. The only source of truth now is the [README file](https://github.com/apify/fingerprint-suite/blob/master/README.md) in the root of the repository, which contains all the important info to get started.
> 
> Do you have any specific question you can't find an answer for? Maybe I can help :)

When I use newInjectedPage together with puppeteer and proxy, my code can't load pages, I wanted to try using other methods - generative-bayesian-network maybe? And in general, to see what methods are available, but since there is no documentation, there may be an answer to the question why when using newInjectedPage + proxy, the page does not load, the code looks primitive, I create a browser instance and call the newInjectedPage method and after page.goto. Proxies are connected in the arguments "--proxy-server=**"

**Comment by barjin** [comment]
Huh, that is curious. As for another way how to use the `fingerprint-suite` tools, you can use the older way of injecting the Puppeteer page with the fingerprint (the `attachFingerprintToPuppeteer` method - see code snippet below). However, I'm not sure whether that will help with your problem, as this is exactly what the `newInjectedPage()` is doing. 

Running an instance of [Squid proxy](http://www.squid-cache.org/) locally on port 3128, the following snippet worked just fine for me. Try testing your proxies without the fingerprinting tools first and see whether they work... Otherwise, I really have no idea what might be causing your problem. 
 
```javascript
const puppeteer = require('puppeteer');
const { FingerprintInjector } = require('fingerprint-injector');
const { FingerprintGenerator } = require('fingerprint-generator');

(async () => {
    const browser = await puppeteer.launch({
        headless: false,
        args: [
            '--proxy-server=127.0.0.1:3128',
        ],

    });

    const fingerprint = await new FingerprintGenerator().getFingerprint({
        devices: ["mobile"],
        operatingSystems: ["android"],
    });

    const page = await browser.newPage();
    await new FingerprintInjector().attachFingerprintToPuppeteer(page, fingerprint);
    
    // ...
})();
```

Check this out and let me know, whether it helped. Good luck!
