### ISSUE TITLE
How i can add fingerprints for all browser pupeeteer ?

### ISSUE THREAD

**Issue by yanchuk-s** [apify/fingerprint-suite#168]
Hello, i need add fingerprints for all browser in pupeeteer, but i can only for one page: 
 
const page = await fingerprint.newInjectedPage(browser, {
     fingerprintOptions: fingerprintOptions,
 });

how i can do this for all pages in browser ?

**Comment by barjin** [comment]
Hi and thank you for submitting this issue!

As of now, with Puppeteer, you can only inject fingerprints to separate pages. While this might seem like a problem, the workaround is very simple - you can easily write a wrapper around the `browser.newPage` method, which automatically calls the injection method:

```javascript
const puppeteer = require('puppeteer');
const { FingerprintInjector } = require('fingerprint-injector');
const { FingerprintGenerator } = require('fingerprint-generator');

(async () => {
    const browser = await puppeteer.launch();

    const fingerprint = await new FingerprintGenerator().getFingerprint({
        devices: ["mobile"],
        operatingSystems: ["android"],
    });

    (() => {
        const originalNewPage = browser.newPage;

        browser.newPage = async function () {
            const page = await originalNewPage.apply(this, arguments);
            await new FingerprintInjector().attachFingerprintToPuppeteer(page, fingerprint);
            return page;
        }
    })();

   // all the pages created from now on will have the fingerprint
    const page = await browser.newPage();
    const page2 = await browser.newPage();
    const page3 = await browser.newPage();
    //...
})();
```

Because JS is such a malleable language, you can overwrite properties of objects on the fly - this way, I can overwrite the original `browser.newPage()` method with a "new" implementation which takes care of the fingerprint injection.

Hope this helps - I will now close this issue, but feel free to ask any follow-up questions in case something is unclear. Cheers!

**Comment by barjin** [comment]
Right, now I realized I might have not answered your question fully. If you want to inject the fingerprint into all the **existing** pages in your browser instance, you can do so with the `attachFingerprintToPuppeteer` method again, see example below:
```javascript
const pages = await browser.pages();

for ( page of pages ) {
    await new FingerprintInjector().attachFingerprintToPuppeteer(page, fingerprint);
}
```

For performance reasons, you might want to use `Promise.all` instead of iterating through the pages, but for the sake of simplicity, this should work just fine :) Just keep in mind you might need to reload the page after injecting the fingerprint in order to really see the results of the injection.
