### ISSUE TITLE
Chrome WebView User-Agent

### ISSUE THREAD

**Issue by yovanoc** [apify/fingerprint-suite#273]
**Describe the feature**
It would be nice, I think, to add an option in the `HeaderGeneratorOptions` to generate WebView only user-agents (maybe only for mobile?)

examples:

- Mozilla/5.0 (Linux; Android 7.0; SM-A310F Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/64.0.3282.137 Mobile Safari/537.36
- Mozilla/5.0 (Linux; Android 13; 2201122G Build/TKQ1.220807.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

**Motivation**
Some fingerprints detections use this to flag certain kind of devices

**Comment by barjin** [comment]
Hello - and thank you for your interest in this project!

We generate all our browser data (headers + Web API values) from data that we collect in regular web traffic. WebView-based requests are unfortunately very scarce in our datasets, so we cannot reliably generate this kind of requests.

Because of that, this is a `wontfix` from me right now - but we're definitely curious if you have any kind of dataset with these kinds of devices collected. Thank you! (and sorry for the `wontfix`).

**Comment by yovanoc** [comment]
Hello!

Can you share me the way you are collecting data please?

I don't have any dataset but I know from sources that some anti-bot services can block by this.
