### ISSUE TITLE
Please update the internal puppeteer version..

### ISSUE THREAD

**Issue by searchingforcode** [apify/fingerprint-suite#63]
![image](https://user-images.githubusercontent.com/1987330/187316156-a77de6f4-5074-4a68-b389-ff31495bd81f.png)

Fingerprint injector package shows it requires up to puppeteer 15.1 version.  Now the latest puppeteer version is 16.2 i think. Is there any plan to update it? And sometime it creates a big conflicts also for the version mismatch of puppeteer.

**Comment by B4nan** [comment]
We update the versions based on supported chrome version because of usage in crawlee and apify platform in general. Those are always few weeks behind the latest stable chromium (and puppeteer versions are based on that).

https://pptr.dev/chromium-support

Current stable is chrome 104, and for that we need to stay on v15.1. I believe chrome 105 should be rolling out this week, so we will update this soon anyway (next week tops).

But it's true we dont have to care about it at the fingerprint suite level, I think it should be safe to remove the upper bound restriction.

Btw latest puppeteer is v17, released yesterday.

**Comment by barjin** [comment]
Will test this and perhaps remove the `peerDeps` constraint, `fingerprint-suite` doesn't use that many specific puppeteer/playwright features, it's mostly about the in-browser JS. If this doesn't break anything, the latest version should be on `npm` soon :)

Thanks @searchingforcode for bringing this up!

**Comment by barjin** [comment]
The `peerDependencies` constraints have been relaxed and `fingerprint-injector` now works (and is tested with) the latest versions of the automation libraries. The updated version is [fingerprint-injector@2.0.7](https://www.npmjs.com/package/fingerprint-injector/v/2.0.7). A few other dependencies have been updated/removed as well. 

Thank you (and sorry for the wait)! Feel free to reopen the issue in case of any problems.
